config/routes.rb
Rails.application.routes.draw do

  # get "/photos/index"
  resources :photos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/photo.rb
# == Schema Information
#
# Table name: photos
#
#  id         :integer          not null, primary key
#  title      :string
#  image_url  :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Photo < ApplicationRecord
  validates :title, presence: true, uniqueness: { message: "El titulo debe ser único" }
  validates :image_url, presence: true, format: { with: /.\.(png|jpeg|jpg|gif)/ , message: "La url no es valida"}
  scope :latest, ->(limit) { order("id desc").limit(limit) }
  scope :paginate_scope, -> (page=1, per_page=15) { order("id desc").offset((page - 1) * per_page).limit(per_page) if per_page && page }

  def self.paginate(page = 1, per_page = 15)
    Photo.order("id desc").offset((page - 1) * per_page).limit(per_page) if page && per_page
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/geolocalizable.rb
module Geolocalizable
  extend ActiveSupport::Concern

  included do
    before_action :set_country_by_ip
  end

  def set_country_by_ip
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: %i[show edit update destroy]
  layout "landing"

  def index
    @photos = Photo.all
  end

  def show
  end

  def new
    session[:intentos] = session[:intentos] ? session[:intentos] + 1 : 1
    @photo = Photo.new
  end

  def edit
    @photo = Photo.find(params[:id])
  end

  def update
    @photo.update(photo_params)

    redirect_to @photo
  end

  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: "Todo salio bien" }
        format.json { render json: @photo, status: :created }
      else
        format.html {
          redirect_back fallback_location: photos_path,
                        notice: "Algo salio mal #{@photo.errors.full_messages.to_sentence}"
        }
      end
    end
  end

  def destroy
    @photo.destroy

    redirect_to photos_path
  end

  private def photo_params
    params.require(:photo).permit(:title, :image_url)
  end

  private def set_photo
    @photo = Photo.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImageGallery</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  
		<nav>
		    <li><% link_to "Inicio", root_path %></li>
		    <li><% link_to "Fotos", photos_path %></li>
		</nav>
		
    <% yield :sidebar_options %>

		<% yield %>
  </body>
</html>

app/views/photos/edit.html.erb
<%= form_with model: @photo do |form| %>

  <div>
    <% @tags.each do |tag| %>
      <%= form.check_box "tag_ids[]", name: "photo[tag_ids]", include_hidden: false %>
    <% end %>
  </div>


  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
      <%= form.label :image_url %>
       <%= form.url_field :image_url %>
  </div>

  <%= form.submit "Enviar" %>
<% end %>

app/views/photos/index.html.erb
<h1>Photos</h1>

<%= content_for :sidebar_options do %>
    <p> Hola desde photos/index </p>
<%end%>

<% @photos.each do |photo| %>
    <div>
        <h2><%= photo.title %> </h2>
        <%= image_tag photo.image_url %>
        <%= link_to "Ver mas", photo %>
    </div>
<% end %>
<br><br><br><br>
<%= link_to "New photo", new_photo_path %>

app/views/photos/new.html.erb
<p>Intentos: <%=session[:intentos]%> </p>

<% form_with model: @photo do |form| %>    
    <div>
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>
    <div>
        <%= form.label :image_url %>
        <%= form.url_field :image_url %>
    </div>

    <%= form.submit "Enviar" %>
<%end%>

app/views/photos/show.html.erb
<h1>Detail</h1>
<div>
	<h2><%= @photo.title %> </h2>
	<%= image_tag @photo.image_url %>
	<div>
		<%= link_to "Editar", edit_photo_path(@photo) %>
		<%= button_to "Eliminar", @photo, method: :delete %>
	</div>

	<br><br><br><br>
	<%= link_to "Ir al menu", "/photos" %>
</div>